"""
empty_pipeline
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
import pendulum


default_args={
    "owner": "jroachgolf84@outlook.com,Open in Cloud IDE",
}

@dag(
    default_args=default_args,
    schedule=None,
    start_date=pendulum.from_format("2023-11-18", "YYYY-MM-DD"),
    catchup=False,
    owner_links={
        "jroachgolf84@outlook.com": "mailto:jroachgolf84@outlook.com",
        "Open in Cloud IDE": "https://cloud.astronomer.io/clp4adpm600ai01nseg4x93h5/cloud-ide/clp4b3v0h00ak01nsepkkan70/clp4b3v6b008w01oyukd6traz",
    },
)
def empty_pipeline():

dag_obj = empty_pipeline()
